# Generated by Django 2.2b1 on 2019-05-10 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='mail_template',
        ),
        migrations.AddField(
            model_name='contactmarketing',
            name='job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketingplan',
            name='mail_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_plans', to='campaigns.MailTemplate'),
        ),
    ]
