# Generated by Django 2.2 on 2019-04-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20190410_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
