# Generated by Django 2.1.7 on 2019-03-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20190323_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactgroup',
            name='contacts',
            field=models.ManyToManyField(related_name='groups', to='contacts.Contact'),
        ),
    ]
