# Generated by Django 2.2 on 2019-04-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20190418_1827'),
        ('orders', '0003_auto_20190418_1827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
