# Generated by Django 2.1.7 on 2019-03-28 14:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0005_note'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactgroup',
            unique_together={('user', 'name')},
        ),
    ]
