# Generated by Django 2.1.7 on 2019-03-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20190328_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10),
        ),
    ]
