# Generated by Django 2.1.7 on 2019-04-03 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0009_auto_20190331_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactgroup',
            name='_type',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE')], default='PRIVATE', max_length=20),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cant_edit_contact_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
    ]
