# Generated by Django 2.1.7 on 2019-04-10 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_auto_20190410_1140'),
        ('events', '0002_auto_20190410_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='marketing_plan',
        ),
        migrations.AddField(
            model_name='event',
            name='marketing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='campaigns.ContactMarketing'),
        ),
        migrations.AlterField(
            model_name='event',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(),
        ),
    ]
