# Generated by Django 2.1 on 2019-04-13 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='action',
        ),
    ]
