# Generated by Django 2.1 on 2019-04-14 14:10

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='histories',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True), default=list, size=None),
        ),
    ]
