# Generated by Django 2.1 on 2019-04-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_histories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='histories',
        ),
    ]
