version: '3'
services:
  web:
    build: .
    environment:
      - PGHOST=postgres
    volumes:
      - .:/codebase
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    restart: always
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5443:5432
  redis:
    image: redis:alpine