version: '3'
services:
  web:
    build: ./api_service
    environment:
      - PGHOST=postgres
    volumes:
      - ./api_service:/codebase
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - elasticsearch
    restart: always
  
  emails:
    build: ./mail_box
    environment:
      - PGHOST=postgres
      - GOOGLE_APPLICATION_CREDENTIALS="${GOOGLE_APPLICATION_CREDENTIALS}"
    volumes:
    - ./mail_box:/codebase
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - redis
      - elasticsearch
    # restart: always

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5443:5432
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.0
    ports:
      - 9200:9200
      - 9300:9300
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379