# Generated by Django 2.1.7 on 2019-03-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='package',
        ),
        migrations.AddField(
            model_name='package',
            name='features',
            field=models.ManyToManyField(related_name='packages', to='packages.Feature'),
        ),
    ]
