# Generated by Django 2.2b1 on 2019-04-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20190419_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='start_support_date',
        ),
        migrations.AlterField(
            model_name='feature',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
