# Generated by Django 2.1.7 on 2019-03-26 18:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20190326_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
        migrations.AddField(
            model_name='package',
            name='prices',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
