# Generated by Django 2.1.7 on 2019-04-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20190327_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='start_sale_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_support_date',
            field=models.DateField(),
        ),
    ]
