# Generated by Django 2.1 on 2019-04-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_auto_20190423_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='start_support_date',
        ),
        migrations.AlterField(
            model_name='feature',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
