export const NOT_AUTHORIZED = 'NOT_AUTHORIZED'
export const FORBIDDEN = 'FORBIDDEN'
export const BAD_REQUEST = 'BAD_REQUEST'
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'

export const STATUS_TOSTRING = {
  400: BAD_REQUEST,
  401: NOT_AUTHORIZED,
  403: FORBIDDEN,
  500: INTERNAL_SERVER_ERROR
}
