# Generated by Django 2.1 on 2019-04-19 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='actions',
        ),
    ]
