# Generated by Django 2.2 on 2019-04-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0002_auto_20190418_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='actions2',
            new_name='actions',
        ),
    ]
