# Generated by Django 2.1 on 2019-04-19 05:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0002_remove_step_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='actions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
