# Generated by Django 2.1 on 2019-05-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0003_step_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepdetail',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed')], default='RUNNING', max_length=50),
        ),
    ]
