# Generated by Django 2.2b1 on 2019-05-06 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0004_stepdetail_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepdetail',
            options={'ordering': ('id',)},
        ),
    ]
