# Generated by Django 2.1 on 2019-05-08 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0029_remove_marketingplan_contacts'),
        ('steps', '0005_auto_20190504_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='nth',
        ),
        migrations.AddField(
            model_name='stepdetail',
            name='mail_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.MailTemplate'),
        ),
    ]
