# Generated by Django 2.1 on 2019-05-09 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0031_auto_20190509_0120'),
        ('steps', '0006_auto_20190508_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepdetail',
            name='mail_template',
        ),
        migrations.AddField(
            model_name='step',
            name='mail_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.MailTemplate'),
        ),
    ]
