# Generated by Django 2.1 on 2019-05-10 14:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0007_auto_20190509_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='conditions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
