# Generated by Django 2.1 on 2019-05-11 14:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0009_auto_20190510_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepdetail',
            name='information',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
