# Generated by Django 2.2.1 on 2019-05-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('message_id', models.CharField(max_length=255)),
                ('message_history', models.CharField(max_length=255)),
            ],
        ),
    ]
