# Generated by Django 2.2.1 on 2019-05-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='thread_id',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
