# Generated by Django 2.2.1 on 2019-05-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_mailbox_thread_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='mailbox',
            name='message_history',
        ),
    ]
