# Generated by Django 2.2b1 on 2019-05-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_auto_20190516_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='email_type',
            field=models.CharField(choices=[('SENT', 'SENT'), ('INBOX', 'INBOX')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
