# Generated by Django 2.2b1 on 2019-05-09 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('orders', '0001_initial'),
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0001_initial'),
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='step_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to='steps.StepDetail'),
        ),
        migrations.AddField(
            model_name='order',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='campaigns.Campaign'),
        ),
        migrations.AddField(
            model_name='order',
            name='contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='contacts.Contact'),
        ),
        migrations.AddField(
            model_name='order',
            name='packages',
            field=models.ManyToManyField(related_name='orders', to='packages.Package'),
        ),
        migrations.AddField(
            model_name='order',
            name='sale_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lifetimelicense',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifetime_licenses', to='orders.Order'),
        ),
        migrations.AddField(
            model_name='lifetimelicense',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages_lifetime_license', to='packages.Package'),
        ),
        migrations.AddField(
            model_name='license',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='orders.Order'),
        ),
        migrations.AddField(
            model_name='license',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages_license', to='packages.Package'),
        ),
    ]
