# Generated by Django 2.2b1 on 2019-04-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190321_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='manager',
        ),
    ]
