# Generated by Django 2.1.7 on 2019-04-10 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_marketingplan_actions2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingplan',
            name='actions',
        ),
    ]
