# Generated by Django 2.1.7 on 2019-04-10 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_remove_marketingplan_actions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingplan',
            old_name='actions2',
            new_name='actions',
        ),
    ]
