# Generated by Django 2.2 on 2019-04-10 06:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20190410_1332'),
        ('campaigns', '0003_auto_20190405_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMarketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('priority', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_marketing_plan', to='campaigns.Campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact')),
                ('marketing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.MarketingPlan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='marketingplan',
            name='contacts',
            field=models.ManyToManyField(related_name='marketing_plans', through='campaigns.ContactMarketing', to='contacts.Contact'),
        ),
    ]
