# Generated by Django 2.1.7 on 2019-04-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20190410_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(),
        ),
    ]
