# Generated by Django 2.2 on 2019-04-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_auto_20190415_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingplan',
            old_name='actions2',
            new_name='actions',
        ),
    ]
