# Generated by Django 2.1.7 on 2019-04-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_auto_20190410_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmarketing',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=2),
        ),
    ]
