# Generated by Django 2.1.7 on 2019-04-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_auto_20190410_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmarketing',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='contactmarketing',
            name='status',
            field=models.TextField(choices=[('FAILED', 'Failed'), ('RUNNING', 'Running'), ('COMPLETED', 'COMPLETED')], default='RUNNING'),
        ),
    ]
