# Generated by Django 2.2b1 on 2019-04-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_auto_20190418_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupplan',
            name='can_modify',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketingplan',
            name='can_modify',
            field=models.BooleanField(default=True),
        ),
    ]
