# Generated by Django 2.1 on 2019-04-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_auto_20190410_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmarketing',
            name='status',
            field=models.TextField(choices=[('FAILED', 'Failed'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed')], default='RUNNING'),
        ),
    ]
