# Generated by Django 2.2b1 on 2019-04-26 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_auto_20190424_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingplan',
            name='contacts',
        ),
    ]
