# Generated by Django 2.1 on 2019-04-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_auto_20190414_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmarketing',
            name='status',
            field=models.TextField(choices=[('FAILED', 'Failed'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='RUNNING'),
        ),
    ]
