# Generated by Django 2.1 on 2019-04-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_auto_20190414_0259'),
        ('campaigns', '0009_auto_20190414_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='packages',
            field=models.ManyToManyField(related_name='campaigns', to='packages.Package'),
        ),
    ]
