# Generated by Django 2.1 on 2019-04-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_campaign_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='packages',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='packages.Package'),
        ),
    ]
