# Generated by Django 2.1 on 2019-04-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20190408_1600'),
        ('campaigns', '0011_auto_20190414_0417'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactmarketing',
            unique_together={('marketing_plan', 'contact')},
        ),
    ]
