# Generated by Django 2.1 on 2019-04-14 14:30

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_auto_20190414_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmarketing',
            name='histories',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True), default=list, size=None),
        ),
    ]
