# Generated by Django 2.1 on 2019-04-14 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_contactmarketinghistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmarketing',
            name='histories',
        ),
        migrations.AlterField(
            model_name='contactmarketinghistory',
            name='contact_marketing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='campaigns.ContactMarketing'),
        ),
    ]
