# Generated by Django 2.1 on 2019-04-15 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_auto_20190415_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='_type',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('MARKETING', 'Marketing'), ('FOLLOWUP', 'Follow up')], default='Default', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='campaigns.Campaign'),
        ),
    ]
