# Generated by Django 2.1 on 2019-04-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20190415_2119'),
        ('campaigns', '0019_auto_20190415_2132'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('campaign', '_type', 'contact')},
        ),
    ]
