# Generated by Django 2.1 on 2019-04-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_auto_20190415_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.TextField(),
        ),
    ]
