# Generated by Django 2.1 on 2019-04-16 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20190415_2119'),
        ('campaigns', '0022_auto_20190416_1317'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactmarketing',
            unique_together={('campaign', 'contact')},
        ),
    ]
