# Generated by Django 2.1 on 2019-04-16 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0023_auto_20190417_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='assigned_to',
            field=models.ManyToManyField(related_name='sale_reps_campaign', to=settings.AUTH_USER_MODEL),
        ),
    ]
