# Generated by Django 2.1 on 2019-04-19 05:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0024_campaign_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingplan',
            name='actions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=8),
        ),
    ]
