# Generated by Django 2.1 on 2019-04-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0025_auto_20190419_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupplan',
            name='can_modify',
            field=models.BooleanField(default=True),
        ),
    ]
