# Generated by Django 2.1 on 2019-04-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0026_followupplan_can_modify'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingplan',
            name='can_modify',
            field=models.BooleanField(default=True),
        ),
    ]
