# Generated by Django 2.1 on 2019-04-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0027_marketingplan_can_modify'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtemplate',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
