# Generated by Django 2.1 on 2019-04-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0028_mailtemplate_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingplan',
            name='contacts',
        ),
    ]
