# Generated by Django 2.1 on 2019-05-09 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0029_remove_marketingplan_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='mail_template',
        ),
        migrations.AddField(
            model_name='contactmarketing',
            name='mail_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='campaigns.MailTemplate'),
        ),
    ]
