# Generated by Django 2.1 on 2019-05-09 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0030_auto_20190509_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmarketing',
            name='mail_template',
        ),
        migrations.AddField(
            model_name='marketingplan',
            name='mail_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_plans', to='campaigns.MailTemplate'),
        ),
    ]
