# Generated by Django 2.2 on 2019-04-15 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('contacts', '0003_auto_20190410_1332'),
        ('packages', '0002_auto_20190415_1027'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='step_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to='steps.StepDetail'),
        ),
        migrations.AddField(
            model_name='order',
            name='contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='contacts.Contact'),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='contacts.Note'),
        ),
        migrations.AddField(
            model_name='order',
            name='packages',
            field=models.ManyToManyField(related_name='orders', to='packages.Package'),
        ),
        migrations.AddField(
            model_name='order',
            name='sale_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
