# Generated by Django 2.1.7 on 2019-04-10 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0012_auto_20190408_1600'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('steps', '0001_initial'),
        ('orders', '0001_initial'),
        ('packages', '0005_auto_20190403_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='step_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to='steps.StepDetail'),
        ),
        migrations.AddField(
            model_name='order',
            name='contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='contacts.Contact'),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='contacts.Note'),
        ),
        migrations.AddField(
            model_name='order',
            name='packages',
            field=models.ManyToManyField(related_name='orders', through='orders.PackageOrder', to='packages.Package'),
        ),
        migrations.AddField(
            model_name='order',
            name='sale_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
