# Generated by Django 2.1.7 on 2019-04-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190410_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('RUNNING', 'Running'), ('COMPLETED', 'COMPLETED')], default='RUNNING', max_length=100),
        ),
    ]
