# Generated by Django 2.2b1 on 2019-05-03 18:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20190426_1117'),
        ('orders', '0004_license_lifetimelicense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='packages',
        ),
        migrations.CreateModel(
            name='OrderPackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('duration', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_packages', to='orders.Order')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_packages', to='packages.Package')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
