# Generated by Django 2.1 on 2019-04-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_auto_20190414_0259'),
        ('orders', '0004_auto_20190414_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packages',
            field=models.ManyToManyField(related_name='orders', to='packages.Package'),
        ),
    ]
