# Generated by Django 2.1 on 2019-04-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('RUNNING', 'Running'), ('COMPLETED', 'COMPLETED'), ('OVERDUE', 'Overdue')], default='RUNNING', max_length=100),
        ),
    ]
