# Generated by Django 2.2b1 on 2019-05-06 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_packages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='packages',
        ),
        migrations.DeleteModel(
            name='OrderPackages',
        ),
    ]
