# Generated by Django 2.2b1 on 2019-05-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20190426_1117'),
        ('orders', '0007_auto_20190506_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packages',
            field=models.ManyToManyField(related_name='orders', to='packages.Package'),
        ),
    ]
