# Generated by Django 2.1 on 2019-04-16 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0024_campaign_assigned_to'),
        ('orders', '0007_remove_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='campaigns.Campaign'),
        ),
    ]
