# Generated by Django 2.1 on 2019-05-03 22:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_auto_20190430_2144'),
        ('orders', '0009_license_lifetimelicense'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('duration', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='packages',
        ),
        migrations.AddField(
            model_name='orderpackages',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_packages', to='orders.Order'),
        ),
        migrations.AddField(
            model_name='orderpackages',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_packages', to='packages.Package'),
        ),
    ]
