# Generated by Django 2.1 on 2019-05-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_auto_20190430_2144'),
        ('orders', '0010_auto_20190503_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packages',
            field=models.ManyToManyField(related_name='orders', through='orders.OrderPackages', to='packages.Package'),
        ),
    ]
