# Generated by Django 2.1 on 2019-05-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_auto_20190430_2144'),
        ('orders', '0012_auto_20190504_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packages',
            field=models.ManyToManyField(related_name='orders', to='packages.Package'),
        ),
    ]
