# Generated by Django 2.1 on 2019-05-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_packages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='step_detail',
        ),
    ]
