# Generated by Django 2.1 on 2019-05-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_orderhistory_step_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'ordering': ('-created',)},
        ),
    ]
