# Generated by Django 2.2b1 on 2019-05-10 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20190510_0824'),
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='nth',
        ),
        migrations.AddField(
            model_name='step',
            name='mail_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.MailTemplate'),
        ),
    ]
